### ISSUE TITLE
Replace OAuth2 Authentication flow

### ISSUE THREAD

**Issue by silvamb** [silvamb/virtwallet-serverless#13]
Initially I created Cognito User pool to support Client Credentials auth flow and the use of scopes. However, with a different auth flow, such as Implicit Grand or Authorization Code the API does not work properly.  

Two actions are needed:
1. Remove from all serverless.yml file the configuration to restrict OAuth2 scope in an API Gateway resource.
For example, from:
```yaml
  events:
    - http:
        path: account
        method: post
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId: ${self:custom.restApiAuthorizerId}
          scopes:
            - email
```
To:
```yaml
  events:
    - http:
        path: account
        method: post
        authorizer:
          type: COGNITO_USER_POOLS
```

2. In the Lambda function the `client_id` field is no longer relevant. Th `aud` field should be used instead.  

Change from:
```javascript
const clientId = event.requestContext.authorizer.claims.client_id;
```
To:
```javascript
const clientId = event.requestContext.authorizer.claims.aud;
```
